# Generated by Django 4.2.21 on 2025-05-24 18:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactmessage",
            name="submitted_at",
        ),
    ]
